### ISSUE TITLE
FR: Use Global or Text field for Brand

### ISSUE THREAD

**Issue by chadcrowell** [studioespresso/craft3-facebook-catalog#1]
Idk about anyone else, but every product in my clients' stores have 1 brand name, and it is not stored as a field that is attached to every product. Is it possibly to either allow selection of a global or a plain text field, or a config file setting, to put the brand name in this plugin? https://d.pr/i/fDXMK1

For now I have hacked the plugin to hard code the brand name.

**Comment by janhenckens** [comment]
Hey Chad, thanks for making an issue for this! Yours is also the first issue here 😀🎉
Adding the option to define a custom value in a text field in the plugin settings seems like a good idea here, not just for the brand value.

Planned on working another feature for the plugin tomorrow, I'll add this to the list.

**Comment by janhenckens** [comment]
Added in 1.2.0.

If you have any other requests, feel free to make an issue!
